version: "3.8"
services:
  neo4j:
    image: neo4j:5.22
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/neo4j1234"
    volumes:
      - neo4j_data:/data

  app:
    build: .
    depends_on:
      - neo4j
    ports:
      - "5000:5000"
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4j1234

volumes:
  neo4j_data:
